-- transparent background
vim.cmd("Normal guibg=NONE")
vim.cmd("NormalFloat guibg=NONE")
vim.cmd("FloatBorder guibg=NONE")
vim.cmd("Pmenu guibg=NONE")
vim.cmd("Terminal guibg=NONE")
vim.cmd("EndOfBuffer guibg=NONE")
vim.cmd("FoldColumn guibg=NONE")
vim.cmd("Folded guibg=NONE")
vim.cmd("SignColumn guibg=NONE")
vim.cmd("NormalNC guibg=NONE")
vim.cmd("WhichKeyFloat guibg=NONE")
vim.cmd("TelescopeBorder guibg=NONE")
vim.cmd("TelescopeNormal guibg=NONE")
vim.cmd("TelescopePromptBorder guibg=NONE")
vim.cmd("TelescopePromptTitle guibg=NONE")

-- transparent background for neotree
vim.cmd("NeoTreeNormal guibg=NONE")
vim.cmd("NeoTreeNormalNC guibg=NONE")
vim.cmd("NeoTreeVertSplit guibg=NONE")
vim.cmd("NeoTreeWinSeparator guibg=NONE")
vim.cmd("NeoTreeEndOfBuffer guibg=NONE")

-- transparent background for nvim-tree
vim.cmd("NvimTreeNormal guibg=NONE")
vim.cmd("NvimTreeVertSplit guibg=NONE")
vim.cmd("NvimTreeEndOfBuffer guibg=NONE")

-- transparent notify background
vim.cmd("NotifyINFOBody guibg=NONE")
vim.cmd("NotifyERRORBody guibg=NONE")
vim.cmd("NotifyWARNBody guibg=NONE")
vim.cmd("NotifyTRACEBody guibg=NONE")
vim.cmd("NotifyDEBUGBody guibg=NONE")
vim.cmd("NotifyINFOTitle guibg=NONE")
vim.cmd("NotifyERRORTitle guibg=NONE")
vim.cmd("NotifyWARNTitle guibg=NONE")
vim.cmd("NotifyTRACETitle guibg=NONE")
vim.cmd("NotifyDEBUGTitle guibg=NONE")
vim.cmd("NotifyINFOBorder guibg=NONE")
vim.cmd("NotifyERRORBorder guibg=NONE")
vim.cmd("NotifyWARNBorder guibg=NONE")
vim.cmd("NotifyTRACEBorder guibg=NONE")
vim.cmd("NotifyDEBUGBorder guibg=NONE")
